"""Initial tables

Revision ID: 3be5f8ba66d8
Revises: 
Create Date: 2026-02-15 15:12:10.617009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3be5f8ba66d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('career_page_url', sa.String(), nullable=False),
    sa.Column('ats_identifier', sa.String(), nullable=True),
    sa.Column('ats_provider', sa.Enum('GREENHOUSE', 'COMEET', 'WORKDAY', 'LEVER', 'API_CUSTOM', name='atsprovider'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_page_url')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'APPLIED', 'ARCHIVED', name='jobstatus'), nullable=False),
    sa.Column('user_verdict', sa.Enum('PERFECT_MATCH', 'GOOD', 'IRRELEVANT', name='userverdict'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'external_id', name='uq_company_job')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('companies')
    # ### end Alembic commands ###
