"""make career_page_url optional

Revision ID: d8ecee687b43
Revises: dd03ceb7fa6d
Create Date: 2026-02-16 01:13:30.193929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ecee687b43'
down_revision: Union[str, Sequence[str], None] = 'dd03ceb7fa6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'career_page_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'career_page_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
