"""Add city to jobs

Revision ID: dd03ceb7fa6d
Revises: d655abd57418
Create Date: 2026-02-15 19:50:26.453463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd03ceb7fa6d'
down_revision: Union[str, Sequence[str], None] = 'd655abd57418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'city')
    # ### end Alembic commands ###
