"""remove ats_identifier

Revision ID: e3fe70788db3
Revises: 0c61673a3c62
Create Date: 2026-02-16 21:43:26.240119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3fe70788db3'
down_revision: Union[str, Sequence[str], None] = '0c61673a3c62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'ats_identifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('ats_identifier', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
